Fix: Update GID handling in devcontainer and Dockerfile for better compatibility

diff --git a/dockling-dev/image/Dockerfile b/dockling-dev/image/Dockerfile
--- a/dockling-dev/image/Dockerfile
+++ b/dockling-dev/image/Dockerfile
@@ -100,8 +100,13 @@ ARG UID=1000
 ARG GID=1000
 ARG DEFAULT_USER=ubuntu
 
-RUN groupmod -g ${GID} ubuntu && \
-    usermod -u ${UID} -g ${GID} ubuntu
+# `groupmod` can fail with exit code 4 when the provided gid is already in use in the container.
+# Our only concern is that the GID of created files match the GID of the user outside the container,
+# so we can use the already existing group with this GID instead of ubuntu group.
+# This is the case for macOS users whose gid is usually 20 (`staff`).
+RUN echo gid ${GID} uid ${UID} expr ${GID:-${UID}}       && \
+    ( groupmod -g ${GID:-${UID}} ubuntu || [ $? == 4 ] ) && \
+    usermod -u ${UID} -g ${GID:-${UID}} ubuntu
 
 RUN if [ "$DEFAULT_USER" = "root" ]; then \
         rm -rf /root/.ssh && ln -s /home/ubuntu/.ssh /root/.ssh; \
