Made deployables cache, but not disrupt tests from running.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -136,6 +136,15 @@ jobs:
         working-directory: ${{ env.WORKSPACE }}
         run: cmake --build ${{ env.BUILD_DIR }} -j 2 -- build_all_tests
 
+      # Check against regressions in target applications.
+      # This step is run now so that the results are cached.
+      # However, it does not fail the job (yet) because we still want the tests to be run.
+      - name: Build deployables
+        id: build-deployables
+        if: ${{ env.BUILD_DEPLOYABLES == 'true' }}
+        run: cmake --build ${{ env.BUILD_DIR }} -- all
+        continue-on-error: true
+
       # Source:  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
       # This step deletes all the cache entries that are related to this branch,
       # and it is done in this moment in the script, right after building, because
@@ -183,10 +192,9 @@ jobs:
           cmake --build ${{ env.BUILD_DIR }} -- coverage
           echo coverage-percent=$(python3 ${{ env.WORKSPACE }}/scripts/cmake/coverage_info_parser.py ${{ env.BUILD_DIR }}/coverage/index.html) > $GITHUB_OUTPUT
 
-      # Check against regressions in target applications.
-      - name: Build deployables
-        if: ${{ env.BUILD_DEPLOYABLES == 'true' }}
-        run: cmake --build ${{ env.BUILD_DIR }} -- all
+      - name: Fail if deployables failed to build
+        if: ${{ env.BUILD_DEPLOYABLES == 'true' && steps.build-deployables.outcome != 'success' }}
+        run: exit 1
 
   coverage:
     needs: [build]
